apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-testing

deploy:
  helm:
    releases:
      - name: k6-operator
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: k6-operator
        namespace: k6-operator-system
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - values/k6-operator-values.yaml
        wait: true
