apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mathtrail-infra-testing

build:
  local:
    push: true
  insecureRegistries:
    - k3d-mathtrail-registry.localhost:5050
  artifacts:
    - image: k3d-mathtrail-registry.localhost:5050/ci-runner
      docker:
        dockerfile: runner/Dockerfile
      context: runner

deploy:
  helm:
    releases:
      - name: k6-operator
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: k6-operator
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/k6-operator-values.yaml
        wait: true
      # Note: github-runner is deployed via justfile deploy recipe
      # to read GITHUB_RUNNER_TOKEN from .env file
